### PR TITLE
fix: Resolve base/head ref & sha to default branch on an issue

### PR DESCRIPTION
**Pull request by rymndhng**
This adds support for slash-command-dispatch on issues in #abcd.

See https://github.com/AbCellera/abcd/pull/11563

### CODE REVIEW

**Comment by rymndhng** [comment]
I can promise you that it typechecked properly 😆 ..

**Review by trent-abc — APPROVED** [review]
low blast radius in any case

**Comment by rymndhng** [comment]
thanks, i'll try this closer to EOD.

**Comment by rymndhng** [comment]
Okay, finally got it working on https://github.com/AbCellera/rayh-github-features-test/actions/runs/11283884612/job/31384117245.

The original code was missing an `await`. Pruning down to a minimal solution now.

**Comment by trent-abc** [comment]
@rymndhng do you think this makes sense to include in an upstream PR or is this more of a special use case for us?  If it should be in the upstream create an [issue](https://github.com/AbCellera/pull-request-comment-branch/issues) and we can hopefully delete this repo once all the issues are merged upstream.  If not then I guess we can just leave it be and continue using this as is

**Comment by rymndhng** [comment]
If the Github DSL for actions were easier to use, I would have preferred to implement this as a conditional check inside the slash command dispatch workflow.

The upstream repo is named `pull-request-comment-branch`, which leads me to believe we're treading outside of the scope of it's original purpose. 

The code for this action is very simple, and the patch is simple. We also only use this in one place right now. 

For these reasons, I don't think it's that risky for us to keep this fork.

**Pull request merged**
